#Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

force_torque_sensor_controller:
  type: "force_torque_sensor_controller/ForceTorqueSensorController"
  publish_rate: 50

# Joint trajectory controller
position_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - gantry_joint_a1
    - gantry_joint_a2
    - gantry_joint_a3
    - gantry_joint_a4
    - gantry_joint_a5
    - gantry_joint_a6
    - gantry_joint_e1
    - gantry_joint_e2
    - gantry_joint_e3
  state_publish_rate: 50 # Defaults to 50
  action_monitor_rate: 20 # Defaults to 20
