position_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
        - joint_e1
        - joint_e2
        - joint_e3
    state_publish_rate: 50 # Defaults to 50
    action_monitor_rate: 20 # Defaults to 20

