controller_list:
  - name: fake_Floor_controller
    joints:
      - floor_joint_a1
      - floor_joint_a2
      - floor_joint_a3
      - floor_joint_a4
      - floor_joint_a5
      - floor_joint_a6
  - name: fake_Gantry_controller
    joints:
      - gantry_joint_e1
      - gantry_joint_e2
      - gantry_joint_e3
      - gantry_joint_a1
      - gantry_joint_a2
      - gantry_joint_a3
      - gantry_joint_a4
      - gantry_joint_a5
      - gantry_joint_a6
  - name: fake_Robot_controller
    joints:
      - floor_joint_a1
      - floor_joint_a2
      - floor_joint_a3
      - floor_joint_a4
      - floor_joint_a5
      - floor_joint_a6
      - gantry_joint_e1
      - gantry_joint_e2
      - gantry_joint_e3
      - gantry_joint_a1
      - gantry_joint_a2
      - gantry_joint_a3
      - gantry_joint_a4
      - gantry_joint_a5
      - gantry_joint_a6
  - name: fake_dummy_floor_eff_controller
    joints:
      []
  - name: fake_dummy_gantry_eff_controller
    joints:
      []