controller_list:
  - name: fake_gantry_robot_controller
    joints:
      - joint_e1
      - joint_e2
      - joint_e3
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
  - name: fake_gantry_controller
    joints:
      - joint_e1
      - joint_e2
      - joint_e3
  - name: fake_robot_controller
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6