controller_list:
  - name: fake_floor_manipulator_controller
    joints:
      - floor_joint_a1
      - floor_joint_a2
      - floor_joint_a3
      - floor_joint_a4
      - floor_joint_a5
      - floor_joint_a6
  - name: fake_gantry_controller
    joints:
      - gantry_joint_e1
      - gantry_joint_e2
      - gantry_joint_e3
  - name: fake_gantry_manipulator_controller
    joints:
      - gantry_joint_a1
      - gantry_joint_a2
      - gantry_joint_a3
      - gantry_joint_a4
      - gantry_joint_a5
      - gantry_joint_a6
  - name: fake_gantry_with_manipulator_controller
    joints:
      - gantry_joint_e1
      - gantry_joint_e2
      - gantry_joint_e3
      - gantry_joint_a1
      - gantry_joint_a2
      - gantry_joint_a3
      - gantry_joint_a4
      - gantry_joint_a5
      - gantry_joint_a6
  - name: fake_robot_controller
    joints:
      - floor_joint_a1
      - floor_joint_a2
      - floor_joint_a3
      - floor_joint_a4
      - floor_joint_a5
      - floor_joint_a6
      - gantry_joint_e1
      - gantry_joint_e2
      - gantry_joint_e3
      - gantry_joint_a1
      - gantry_joint_a2
      - gantry_joint_a3
      - gantry_joint_a4
      - gantry_joint_a5
      - gantry_joint_a6
  - name: fake_eff_floor_controller
    joints:
      []
  - name: fake_eff_gantry_controller
    joints:
      []