# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  floor_joint_a1:
    has_velocity_limits: true
    max_velocity: 2.72271363311
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14159
    min_position: -3.14159
  floor_joint_a2:
    has_velocity_limits: true
    max_velocity: 2.72271363311
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 0.523599
    min_position: -2.61799
  floor_joint_a3:
    has_velocity_limits: true
    max_velocity: 2.72271363311
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 2.42601
    min_position: -2.18166
  floor_joint_a4:
    has_velocity_limits: true
    max_velocity: 5.75958653158
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 6.02139
    min_position: -6.02139
  floor_joint_a5:
    has_velocity_limits: true
    max_velocity: 5.75958653158
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 2.18166
    min_position: -2.18166
  floor_joint_a6:
    has_velocity_limits: true
    max_velocity: 10.7337748998
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 6.02139
    min_position: -6.02139
  gantry_joint_a1:
    has_velocity_limits: true
    max_velocity: 2.72271363311
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 3.14159
    min_position: -3.14159
  gantry_joint_a2:
    has_velocity_limits: true
    max_velocity: 2.72271363311
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 0.523599
    min_position: -2.61799
  gantry_joint_a3:
    has_velocity_limits: true
    max_velocity: 2.72271363311
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 2.42601
    min_position: -2.18166
  gantry_joint_a4:
    has_velocity_limits: true
    max_velocity: 5.75958653158
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 6.02139
    min_position: -6.02139
  gantry_joint_a5:
    has_velocity_limits: true
    max_velocity: 5.75958653158
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 2.18166
    min_position: -2.18166
  gantry_joint_a6:
    has_velocity_limits: true
    max_velocity: 10.7337748998
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 6.02139
    min_position: -6.02139
  gantry_joint_e1:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 1.530
    min_position: 0.010
  gantry_joint_e2:
    has_velocity_limits: true
    max_velocity: 0.83
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 4.690
    min_position: 0.010
  gantry_joint_e3:
    has_velocity_limits: true
    max_velocity: 0.55
    has_acceleration_limits: false
    max_acceleration: 0
    max_position: 0.010
    min_position: -1.590

