gantry_joint_a1_controller:
  type: position_controllers/JointPositionController
  joint: gantry_joint_a1
  pid:
    p: 10.0
    i: 0.01
    d: 0.8
gantry_joint_a2_controller:
  type: position_controllers/JointPositionController
  joint: gantry_joint_a2
  pid:
    p: 10.0
    i: 0.01
    d: 0.8
gantry_joint_a3_controller:
  type: position_controllers/JointPositionController
  joint: gantry_joint_a3
  pid:
    p: 10.0
    i: 0.01
    d: 0.8
gantry_joint_a4_controller:
  type: position_controllers/JointPositionController
  joint: gantry_joint_a4
  pid:
    p: 10.0
    i: 0.01
    d: 0.8
gantry_joint_a5_controller:
  type: position_controllers/JointPositionController
  joint: gantry_joint_a5
  pid:
    p: 10.0
    i: 0.01
    d: 0.8
gantry_joint_a6_controller:
  type: position_controllers/JointPositionController
  joint: gantry_joint_a6
  pid:
    p: 10.0
    i: 0.01
    d: 0.8
gantry_joint_e1_controller:
  type: position_controllers/JointPositionController
  joint: gantry_joint_e1
  pid:
    p: 20.0
    i: 0.01
    d: 0.8
gantry_joint_e2_controller:
  type: position_controllers/JointPositionController
  joint: gantry_joint_e2
  pid:
    p: 20.0
    i: 0.01
    d: 0.8
gantry_joint_e3_controller:
  type: position_controllers/JointPositionController
  joint: gantry_joint_e3
  pid:
    p: 20.0
    i: 0.01
    d: 0.8
floor_joint_a1_controller:
  type: position_controllers/JointPositionController
  joint: floor_joint_a1
  pid:
    p: 1.0
    i: 0.01
    d: 0.8
floor_joint_a2_controller:
  type: position_controllers/JointPositionController
  joint: floor_joint_a2
  pid:
    p: 1.0
    i: 0.01
    d: 0.8
floor_joint_a3_controller:
  type: position_controllers/JointPositionController
  joint: floor_joint_a3
  pid:
    p: 1.0
    i: 0.01
    d: 0.8
floor_joint_a4_controller:
  type: position_controllers/JointPositionController
  joint: floor_joint_a4
  pid:
    p: 1.0
    i: 0.01
    d: 0.8
floor_joint_a5_controller:
  type: position_controllers/JointPositionController
  joint: floor_joint_a5
  pid:
    p: 1.0
    i: 0.01
    d: 0.8
floor_joint_a6_controller:
  type: position_controllers/JointPositionController
  joint: floor_joint_a6
  pid:
    p: 1.0
    i: 0.01
    d: 0.8
